version : '3.8'
services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cerp_root
    #      - MYSQL_DATABASE=cerp
    volumes:
      - ./.mysql_data:/var/lib/mysql
    networks:
      springboot-mysql-net:

  service-registry:
    build:
      context: ./service-registry/
      dockerfile: Dockerfile
    networks:
      service-registry-client:
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    links:
      - service-registry
    networks:
      service-registry-client:
    environment:
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    ports:
      - "9191:9191"
    depends_on:
      - service-registry

  admin-service:
    build:
      context: ./admin-service/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      springboot-mysql-net:
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=cerp_root
      - SPRING_REDIS_HOST=redis
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    depends_on:
      - service-registry
      - api-gateway
      - database
      - redis

  student-service:
    build:
      context: ./student-service/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      springboot-mysql-net:
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=cerp_root
      - SPRING_REDIS_HOST=redis
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    depends_on:
      - service-registry
      - api-gateway
      - database
      - redis

networks:
  springboot-mysql-net:
    driver: bridge
  service-registry-client:
    driver: bridge