server:
  port: 8082

spring:
  application:
    name: STUDENT-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cerp-student?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/